name: Deploy to Staging
run-name: staging-deploy
on: [workflow_dispatch]
jobs:
  filter-branches:
    runs-on: ubuntu-latest
    steps:
      # grep . will exit if the awk fails
      # Ensures branch this workflow is ran on matches the release-v## or release-v##.# pattern
      - run: echo $GITHUB_REF
      - run: echo $GITHUB_REF | awk '/^release-v[0-9]+(\.[0-9]+)?$/' | grep .
  prepare-release-notes:
    needs: filter-branches
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: prepare
        run: |
            git fetch $GITHUB_SHA
            git log --oneline origin/staging..$GITHUB_SHA
  qa-approval:
    environment: 'staging-qa'
    runs-on: ubuntu-latest
    needs: prepare-release-notes
    steps:
      - run: echo "QA approved"
  eng-approval:
    environment: 'staging-eng'
    runs-on: ubuntu-latest
    needs: prepare-release-notes
    steps:
      - run: echo "Engineering approved"
  deploy-to-staging:
    runs-on: ubuntu-latest
    needs: [prepare-release-notes, qa-approval, eng-approval]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          git config user.name "Github Action Bot"
          git config user.email "foo@bar.com"
          git fetch origin staging --depth=1
          git fetch origin ${{ needs.prepare-release-notes.outputs.main-hash }}
          git checkout staging
          git reset --hard ${{ needs.prepare-release-notes.outputs.main-hash }}
          git push -u origin staging --force
