name: Deploy to Staging
run-name: staging-deploy
on: [workflow_dispatch]
jobs:
  prepare-release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git log --oneline staging..main
  deploy-to-staging:
    environment: 'prod'
    runs-on: ubuntu-latest
    steps:
      - use: actions/checkout@v3
      - run: |
        git config user.name "Github Action Bot"
        git config user.email "foo@bar.com"
        git checkout staging
        git reset --hard main
        git push -u origin staging