name: Deploy to Staging
run-name: staging-deploy
on: [workflow_dispatch]
jobs:
  prepare-release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: prepare
        run: |
            git log --oneline origin/staging..origin/main
            echo "hash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
    outputs:
      main-hash: ${{ steps.prepare.outputs.hash }}
  deploy-to-staging:
    environment: 'prod'
    runs-on: ubuntu-latest
    needs: prepare-release-notes
    steps:
      - uses: actions/checkout@v3
      - run: |
          git config user.name "Github Action Bot"
          git config user.email "foo@bar.com"
          git checkout staging
          git reset --hard ${{ needs.prepare-release-notes.outputs.main-hash }}
          git push -u origin staging
